#
# Installing Elasticsearch
# 

# Add Elasticsearch apt key

- name: Add Elasticsearch apt key
  apt_key:
   url: "https://packages.elastic.co/GPG-KEY-elasticsearch"
   state: present

# Installing APT repository
- name: Install APT repository
  apt:
    name: apt-transport-https
    state: present

# Add the Elasticsearch

- name: Adding Elasticsearch repo
  apt_repository
   repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
   state: present

- name: Install Elasticsearch
  apt:
    name: elasticsearch
    update_cache: yes

# Update elasticsearch

- name: Updating the config file
  lineinfile:
  destfile: /etc/elasticsearch/elasticsearch.yml
  regexp: 'network.host:'
  line: 'network.host: 0.0.0.0'
# Update ELastic
- name: Updating the port in config
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: 'http.port:'
   line: 'http.port: 9200'

# Update Elasticsearch port in config

- name: Updating the port
  lineinfile:
   destfile: /etc/elasticsearch/elasticsearch.yml
   regexp: 'cluster.initial_master_nodes:'
   line: 'cluster.initial_master_nodes: ["{{ ansible_default_ipv4.address }}"]'

# Start Elasticsearch

- name: Starting Elasticsearch
  service:
   name: elasticsearch
   state: started


