---
- hosts: all
  become: true
  tasks: 
  - name: install httpd
    apt: 
      name: apache2
      state: latest
    when: ansible_distribution == "Ubuntu"
  - name: install httpd (CentOs)
    dnf: 
      name: httpd
      state: latest
    when: ansible_distribution == "CentOs"
